name: Build Clash Core
on: 
  workflow_dispatch:
    inputs:
      # note: https://github.com/Dreamacro/clash/blob/master/Makefile
      target:
        required: true
        default: 'windows-amd64'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          repository: 'Dreamacro/clash'
          ref: 'dev'
          fetch-depth: 0

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies, run test
        run: |
          go test ./...

      - name: Build
        env:
          NAME: clash
          BINDIR: bin
        run: make -j ${{ github.event.inputs.target }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/*
