name: Build Clash Core
on: 
  workflow_dispatch:
    inputs:
      target:
        required: true
        default: 'windows-amd64'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: 'Dreamacro/clash'
          ref: 'dev'
          fetch-depth: 0

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies, run test and static check
        run: |
          go test ./...
          go vet ./...
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -- $(go list ./...)
      - name: Build
        env:
          NAME: clash
          BINDIR: bin
        run: make -j ${{ github.event.inputs.target }}

      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          path: bin/*
