name: Build CI

on: 
  workflow_dispatch:
#  push:
#    branches: [ master ]

env:
  WARN_ON_PR: "artifact upload is disabled due to the workflow is trigged by pull request."

jobs:
  gradle:
    name: Gradle CI Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone upstream repository
        with:
          repository: 'ejiaogl/FuckCoolapk'
      - uses: actions/checkout@v2
        name: clone my files
        with:
          path: ./my
      - run: mv -f my/FuckCoolapk/* ./

      - name: Prepare Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project
        run: |
          gradle wrapper
          bash gradlew build

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGN_FILE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Get Apk Info
        id: apk
        uses: JantHsueh/get-apk-info-action@master
        with:
          apkPath: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: upload artifact
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: fuckcoolapk_${{steps.apk.outputs.versionNum}}_${{steps.apk.outputs.versionCode}}.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Setup jre
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre
      - name: xpatch
        run: java -jar xpatch.jar Coolapk.apk -xm ${{steps.sign_app.outputs.signedReleaseFile}} -o ./Coolapk-xposed.apk
      - name: upload xpatch apk
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: coolapk-xpatch
          path: ./Coolapk-xposed.apk
