# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Apk

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: 183
      repo:
        required: true
        default: 'Haleydu/Cimoc'
      ref:
        required: true
         default: 'release-tci'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ github.event.inputs.repo }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        TRAVIS_BUILD_NUMBER: ${{ github.event.inputs.version }}
      run: ./gradlew assembleRelease --build-cache --parallel -Dorg.gradle.jvmargs="-XX:MaxHeapSize=2048m -Xmx4608M"
    - name: upload artifact
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: cimoc
        path: ./app/build/outputs/apk/release
