name: Build mihon/yokai
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        default: 'null2264/yokai'
      ref:
        required: false
        default: ''
      debug:
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
      - name: customize
        run: |
          APP_NAME=$(echo "${{ github.event.inputs.repo }}" | awk -F'/' '{print $NF}')
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          #disable warnings for large updates
          sed -i 's/largestSourceSize > MANGA_PER_SOURCE_QUEUE_WARNING_THRESHOLD/false/' app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@a4d662095a2f2af1ed24f1228eb6e55b0f9f1f29
        with:
          java: 17
          distro: temurin

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties || true

      - name: Extract branch name
        id: branch_name
        shell: bash
        run: echo "NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Get changelog
        id: changelog
        shell: bash
        run: |
          {
            echo "CHANGELOG<<END_OF_FILE"
            cat CHANGELOG.md || echo ""
            echo
            echo "END_OF_FILE"
          } >> "$GITHUB_OUTPUT" 2> /dev/null

      # PROD
      - name: Build release build
        if: ${{ inputs.debug != true }}
        run: ./gradlew assembleStandardRelease

      - name: Build debug build
        if: ${{ inputs.debug == true }}
        run: ./gradlew assembleStandardDebug

      - name: Get version stage
        id: version_stage
        shell: bash
        run: |
          echo "STAGE=${{ inputs.debug == true && 'debug' || 'release' }}" >> $GITHUB_OUTPUT
          echo "DIR=${{ inputs.debug == true && 'app/build/outputs/apk/standard/debug' || 'app/build/outputs/apk/standard/release' }}" >> $GITHUB_OUTPUT

      - name: Sign APK
        uses: null2264/actions/android-signer@a4d662095a2f2af1ed24f1228eb6e55b0f9f1f29
        with:
          releaseDir: ${{ steps.version_stage.outputs.DIR }}
          signingKeyBase64: ${{ secrets.SIGN_FILE_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          summarise: true


      - name: Clean up build artifacts
        run: |
          set -e

          dir="${{ steps.version_stage.outputs.DIR }}"

          mv $dir/app-standard-universal-*-signed.apk ${{ env.APP_NAME }}.apk

          cp $dir/app-standard-arm64-v8a-*-signed.apk ${{ env.APP_NAME }}-arm64-v8a.apk

          cp $dir/app-standard-armeabi-v7a-*-signed.apk ${{ env.APP_NAME }}-armeabi-v7a.apk

          cp $dir/app-standard-x86-*-signed.apk ${{ env.APP_NAME }}-x86.apk
          
          cp $dir/app-standard-x86_64-*-signed.apk ${{ env.APP_NAME }}-x86_64.apk

      - name: upload universal
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.APP_NAME }}.apk

      - name: upload arm64-v8a
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ env.APP_NAME }}-arm64-v8a
          path: ${{ env.APP_NAME }}-arm64-v8a.apk

      - name: upload armeabi-v7a
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ env.APP_NAME }}-armeabi-v7a
          path: ${{ env.APP_NAME }}-armeabi-v7a.apk

      - name: upload x86
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ env.APP_NAME }}-x86
          path: ${{ env.APP_NAME }}-x86.apk

      - name: upload x86_64
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ env.APP_NAME }}-x86_64
          path: ${{ env.APP_NAME }}-x86_64.apk
